#!/bin/bash

function GetOne()
{
	local fill="$1"
	local xangle="$2"
	local ds="$3"
	local search="$4"

	# make work directory
	local dir="$top_dir/fill_$fill/xangle_$xangle/$ds/"
	mkdir -p "$dir"

	# get input files
	input_files=""
	for f in `eos ls "$eos_dir"|grep "$search"|grep ".root"`
	do
		if [ -n "$input_files" ]
		then
			input_files="$input_files,\n"
		fi

		input_files="${input_files}    \"root://eostotem.cern.ch/${eos_dir}/${f}\""
	done

	# make config with input files
	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.vstring("
		echo -e "$input_files"
		echo ")"
	) > "$dir/input_files.py"

	# if not present, make (default) config
	if [ ! -f "$dir/config.py" ]
	then
		cp "config_template.py" "$dir/config.py"
	fi
}

#----------------------------------------------------------------------------------------------------

top_dir="../data/alig"
eos_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_September/version5"

GetOne "6228" "150" "DS1" "run_303652"
GetOne "6228" "130" "DS1" "run_303658"
GetOne "6228" "110" "DS1" "run_303665"
